### ISSUE TITLE
Map rendering and lightning generation bug

### ISSUE THREAD

**Issue by specialTT** [Legomountain14/No_Sky_Limits#1]
After installing this datapack (I installed the mod version), the map rendering will become very weird, and the terrain cannot be drawn. Also, lightning will not be generated naturally during thunderstorms, nor will it be generated through a trident. Maybe there is something wrong with my mod pack, please test it.

**Comment by Legomountain14** [comment]
Sorry for the late reply, I noticed the same issue with the map rendering, and I will look at the trident bug. I believe there might be a limit for lightning height, so that lightning won't spawn for example, 100 blocks below the top of the world. Don't take this too seriously though, it's just my speculation. I will get to this later.

**Comment by Legomountain14** [comment]
I think I fixed it, although I can't test it right now. I will push an update if this fix works. (i accidentially set "has_ceiling" to true. I set it to false) 
![image](https://github.com/user-attachments/assets/81ecdc0c-f311-4092-bef5-d829f6e1fb12)

**Comment by Legomountain14** [comment]
Fixed in the latest update!
